"""Add timetable_entries table

Revision ID: 2cf9ab210dbd
Revises: c70b66bcba46
Create Date: 2026-08-29 23:43:01.996400

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2cf9ab210dbd'
down_revision: Union[str, Sequence[str], None] = 'c70b66bcba46'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('timetable_entries',
    sa.Column('entry_id', sa.String(), nullable=False),
    sa.Column('origin', sa.String(), nullable=False),
    sa.Column('destination', sa.String(), nullable=False),
    sa.Column('departure_time', sa.String(), nullable=False),
    sa.Column('data_source', sa.Enum('OFFICIAL', 'OPERATOR', 'VERIFIED_LOCAL', 'SIMULATION', 'DEMO', 'EXTERNAL_PROVIDER', 'MANUAL', name='datasource'), nullable=False),
    sa.Column('source_name', sa.String(), nullable=True),
    sa.Column('source_document', sa.String(), nullable=True),
    sa.Column('parcel_eligible', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('entry_id')
    )
    op.create_index(op.f('ix_timetable_entries_destination'), 'timetable_entries', ['destination'], unique=False)
    op.create_index(op.f('ix_timetable_entries_origin'), 'timetable_entries', ['origin'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_timetable_entries_origin'), table_name='timetable_entries')
    op.drop_index(op.f('ix_timetable_entries_destination'), table_name='timetable_entries')
    op.drop_table('timetable_entries')
    # ### end Alembic commands ###
