"""Add parcel verification codes

Revision ID: 80930f03fe33
Revises: d2f5a9646c4d
Create Date: 2026-08-29 19:02:08.916573

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80930f03fe33'
down_revision: Union[str, Sequence[str], None] = 'd2f5a9646c4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parcels', sa.Column('pickup_verification_code', sa.String(), nullable=True))
    op.add_column('parcels', sa.Column('delivery_verification_code', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('parcels', 'delivery_verification_code')
    op.drop_column('parcels', 'pickup_verification_code')
    # ### end Alembic commands ###
