"""Add valid_from and valid_until to transport models

Revision ID: c70b66bcba46
Revises: 80930f03fe33
Create Date: 2026-08-29 21:19:52.613815

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c70b66bcba46'
down_revision: Union[str, Sequence[str], None] = '80930f03fe33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('buses', sa.Column('valid_from', sa.DateTime(), nullable=True))
    op.add_column('buses', sa.Column('valid_until', sa.DateTime(), nullable=True))
    op.add_column('routes', sa.Column('valid_from', sa.DateTime(), nullable=True))
    op.add_column('routes', sa.Column('valid_until', sa.DateTime(), nullable=True))
    op.add_column('schedules', sa.Column('valid_from', sa.DateTime(), nullable=True))
    op.add_column('schedules', sa.Column('valid_until', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('schedules', 'valid_until')
    op.drop_column('schedules', 'valid_from')
    op.drop_column('routes', 'valid_until')
    op.drop_column('routes', 'valid_from')
    op.drop_column('buses', 'valid_until')
    op.drop_column('buses', 'valid_from')
    # ### end Alembic commands ###
