"""Initial migration

Revision ID: d2f5a9646c4d
Revises: 
Create Date: 2026-08-29 18:43:16.381235

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2f5a9646c4d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('buses',
    sa.Column('bus_id', sa.String(), nullable=False),
    sa.Column('bus_number', sa.String(), nullable=True),
    sa.Column('service_type', sa.String(), nullable=True),
    sa.Column('operator', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('parcel_enabled', sa.Boolean(), nullable=True),
    sa.Column('data_source', sa.Enum('OFFICIAL', 'OPERATOR', 'VERIFIED_LOCAL', 'SIMULATION', 'DEMO', name='datasource'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('bus_id')
    )
    op.create_index(op.f('ix_buses_bus_number'), 'buses', ['bus_number'], unique=True)
    op.create_table('routes',
    sa.Column('route_id', sa.String(), nullable=False),
    sa.Column('route_name', sa.String(), nullable=True),
    sa.Column('origin', sa.String(), nullable=True),
    sa.Column('destination', sa.String(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('data_source', sa.Enum('OFFICIAL', 'OPERATOR', 'VERIFIED_LOCAL', 'SIMULATION', 'DEMO', name='datasource'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('route_id')
    )
    op.create_index(op.f('ix_routes_route_name'), 'routes', ['route_name'], unique=False)
    op.create_table('rural_shipments',
    sa.Column('shipment_id', sa.String(), nullable=False),
    sa.Column('producer_name', sa.String(), nullable=True),
    sa.Column('producer_phone', sa.String(), nullable=True),
    sa.Column('commodity', sa.String(), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('destination', sa.String(), nullable=True),
    sa.Column('preferred_date', sa.String(), nullable=True),
    sa.Column('preferred_time', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('shipment_id')
    )
    op.create_table('traffic_events',
    sa.Column('traffic_event_id', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('severity', sa.String(), nullable=True),
    sa.Column('detected_at', sa.DateTime(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('traffic_event_id')
    )
    op.create_table('route_segments',
    sa.Column('segment_id', sa.String(), nullable=False),
    sa.Column('route_id', sa.String(), nullable=True),
    sa.Column('from_stop', sa.String(), nullable=True),
    sa.Column('to_stop', sa.String(), nullable=True),
    sa.Column('sequence', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['route_id'], ['routes.route_id'], ),
    sa.PrimaryKeyConstraint('segment_id')
    )
    op.create_table('route_stops',
    sa.Column('route_id', sa.String(), nullable=False),
    sa.Column('stop_id', sa.String(), nullable=False),
    sa.Column('stop_sequence', sa.Integer(), nullable=True),
    sa.Column('stop_name', sa.String(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['route_id'], ['routes.route_id'], ),
    sa.PrimaryKeyConstraint('route_id', 'stop_id')
    )
    op.create_table('schedules',
    sa.Column('schedule_id', sa.String(), nullable=False),
    sa.Column('bus_id', sa.String(), nullable=True),
    sa.Column('route_id', sa.String(), nullable=True),
    sa.Column('service_date', sa.String(), nullable=True),
    sa.Column('departure_time', sa.String(), nullable=True),
    sa.Column('arrival_time', sa.String(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('data_source', sa.Enum('OFFICIAL', 'OPERATOR', 'VERIFIED_LOCAL', 'SIMULATION', 'DEMO', name='datasource'), nullable=True),
    sa.ForeignKeyConstraint(['bus_id'], ['buses.bus_id'], ),
    sa.ForeignKeyConstraint(['route_id'], ['routes.route_id'], ),
    sa.PrimaryKeyConstraint('schedule_id')
    )
    op.create_table('parcel_capacity',
    sa.Column('capacity_id', sa.String(), nullable=False),
    sa.Column('bus_id', sa.String(), nullable=True),
    sa.Column('schedule_id', sa.String(), nullable=True),
    sa.Column('segment_id', sa.String(), nullable=True),
    sa.Column('max_safe_parcel_capacity_kg', sa.Float(), nullable=True),
    sa.Column('reserved_capacity_kg', sa.Float(), nullable=True),
    sa.Column('data_source', sa.Enum('OFFICIAL', 'OPERATOR', 'VERIFIED_LOCAL', 'SIMULATION', 'DEMO', name='datasource'), nullable=True),
    sa.Column('capacity_status', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['bus_id'], ['buses.bus_id'], ),
    sa.ForeignKeyConstraint(['schedule_id'], ['schedules.schedule_id'], ),
    sa.ForeignKeyConstraint(['segment_id'], ['route_segments.segment_id'], ),
    sa.PrimaryKeyConstraint('capacity_id')
    )
    op.create_table('parcels',
    sa.Column('parcel_id', sa.String(), nullable=False),
    sa.Column('tracking_id', sa.String(), nullable=True),
    sa.Column('sender_name', sa.String(), nullable=True),
    sa.Column('sender_phone', sa.String(), nullable=True),
    sa.Column('receiver_name', sa.String(), nullable=True),
    sa.Column('receiver_phone', sa.String(), nullable=True),
    sa.Column('source_stop', sa.String(), nullable=True),
    sa.Column('destination_stop', sa.String(), nullable=True),
    sa.Column('weight_kg', sa.Float(), nullable=True),
    sa.Column('volume_m3', sa.Float(), nullable=True),
    sa.Column('parcel_type', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('assigned_schedule_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_schedule_id'], ['schedules.schedule_id'], ),
    sa.PrimaryKeyConstraint('parcel_id')
    )
    op.create_index(op.f('ix_parcels_tracking_id'), 'parcels', ['tracking_id'], unique=True)
    op.create_table('parcel_events',
    sa.Column('event_id', sa.String(), nullable=False),
    sa.Column('parcel_id', sa.String(), nullable=True),
    sa.Column('event_type', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['parcel_id'], ['parcels.parcel_id'], ),
    sa.PrimaryKeyConstraint('event_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('parcel_events')
    op.drop_index(op.f('ix_parcels_tracking_id'), table_name='parcels')
    op.drop_table('parcels')
    op.drop_table('parcel_capacity')
    op.drop_table('schedules')
    op.drop_table('route_stops')
    op.drop_table('route_segments')
    op.drop_table('traffic_events')
    op.drop_table('rural_shipments')
    op.drop_index(op.f('ix_routes_route_name'), table_name='routes')
    op.drop_table('routes')
    op.drop_index(op.f('ix_buses_bus_number'), table_name='buses')
    op.drop_table('buses')
    # ### end Alembic commands ###
